add delete topic command
segmentio/topicctl pull request #100
Opened 2022-10-06 06:21 UTC by rislah

Repl has been set to read only mode to prevent accidental deletes, configurable through CLI flag.

Delete operation must be confirmed with a yes/no

2022-10-14 18:15 UTC, hhahn-tw requested changes
Hello, and thank you for your pull request. I'm sure many will be happy to be able to delete topics via topicctl and we appreciate your contribution.

After some deliberation, we've come to a consensus that the changes to make the repl mode write-capable do not fit the design goals at this time. It is something to consider in the future but it would make more sense as a part of a larger comprehensive overhaul rather than a singleton use case.

Could you resubmit without the repl changes?

2022-10-14 18:15 UTC, hhahn-tw commented on pkg/cli/cli.go
> +	confirm, err := apply.Confirm(fmt.Sprintf("Delete topic \"%s\"", topic), false)
This asks for confirmation without verifying it's an existing topic which can be confusing. In the interest of taking every step to confirm safe operation, can you add a check here that a topic of the given name exists prior to asking user confirmation?

2022-10-14 18:15 UTC, hhahn-tw commented on cmd/topicctl/subcmd/delete.go
> +			"Supported types currently include: topic.",
I don't see any other obvious resource types a delete function would be applicable to - did you have something in mind?

2023-11-09 15:50 UTC, petedannemann commented
Superseding this with https://github.com/segmentio/topicctl/pull/163 due to inactivity

2023-11-09 15:50 UTC, closed without merging